/** Auto-generated by scripts/refresh-image-assets.cjs — do not edit manually. */
export type ImageSize = { width: number; height: number };

const IMAGE_SIZES: Record<string, ImageSize> = {
  "/images/2.webp": { width: 1280, height: 960 },
  "/images/collageOutDoor-1.jpg": { width: 225, height: 225 },
  "/images/collageOutDoor-1.webp": { width: 225, height: 225 },
  "/images/collageOutDoor-2.jpg": { width: 1920, height: 495 },
  "/images/collageOutDoor-2.webp": { width: 1920, height: 495 },
  "/images/footer-logo.webp": { width: 150, height: 150 },
  "/images/kuttaottam.webp": { width: 875, height: 665 },
  "/images/logo.webp": { width: 1000, height: 413 },
  "/images/placements_and_passouts_2k25.webp": { width: 1000, height: 1600 },
  "/images/scholarship.webp": { width: 1275, height: 1800 },
};

export function getImageSize(src: string): ImageSize | undefined {
  return IMAGE_SIZES[src];
}
