/**
 * Resize oversized images only — preserves visual quality (no aggressive recompression).
 * Usage: node scripts/optimize-images.cjs
 */
const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const root = path.join(__dirname, "..");
const imagesDir = path.join(root, "public", "images");
const sizesOut = path.join(root, "lib", "image-sizes.ts");

const MAX_WIDTH = 1920;
const JPEG_QUALITY = 92;
const WEBP_QUALITY = 90;
const SKIP = new Set(["placeholder-campus.svg", "placeholder-lab.svg", "logo.webp"]);

function replaceFile(tmp, input) {
  try {
    fs.renameSync(tmp, input);
  } catch {
    fs.copyFileSync(tmp, input);
    fs.unlinkSync(tmp);
  }
}

async function optimizeFile(file) {
  const input = path.join(imagesDir, file);
  const ext = path.extname(file).toLowerCase();
  const sizesKey = `/images/${file}`;

  const meta = await sharp(input).metadata();
  const w = meta.width ?? 0;
  const h = meta.height ?? 0;
  const before = fs.statSync(input).size;

  if (w <= MAX_WIDTH) {
    console.log(`  ${file}: ${w}×${h} — kept (${Math.round(before / 1024)}KB, within max width)`);
    return { key: sizesKey, width: w, height: h };
  }

  const targetH = Math.max(1, Math.round((h / w) * MAX_WIDTH));
  const tmp = `${input}.opt`;
  let pipeline = sharp(input).rotate().resize({
    width: MAX_WIDTH,
    height: targetH,
    fit: "inside",
    withoutEnlargement: true,
  });

  if (ext === ".jpg" || ext === ".jpeg") {
    await pipeline
      .jpeg({ quality: JPEG_QUALITY, mozjpeg: true, chromaSubsampling: "4:4:4" })
      .toFile(tmp);
  } else if (ext === ".webp") {
    await pipeline.webp({ quality: WEBP_QUALITY, effort: 4 }).toFile(tmp);
  } else {
    return { key: sizesKey, width: w, height: h };
  }

  const after = fs.statSync(tmp).size;
  replaceFile(tmp, input);
  const finalMeta = await sharp(input).metadata();
  console.log(
    `  ${file}: ${w}×${h} → ${finalMeta.width}×${finalMeta.height} (${Math.round(before / 1024)}KB → ${Math.round(after / 1024)}KB)`,
  );

  return {
    key: sizesKey,
    width: finalMeta.width ?? w,
    height: finalMeta.height ?? h,
  };
}

async function writeImageSizes(entries) {
  const logoMeta = await sharp(path.join(imagesDir, "logo.webp")).metadata();
  entries["/images/logo.webp"] = {
    width: logoMeta.width ?? 280,
    height: logoMeta.height ?? 72,
  };

  const lines = [
    "/** Auto-generated by scripts/optimize-images.cjs — do not edit manually. */",
    "export type ImageSize = { width: number; height: number };",
    "",
    "const IMAGE_SIZES: Record<string, ImageSize> = {",
    ...Object.entries(entries)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([k, v]) => `  "${k}": { width: ${v.width}, height: ${v.height} },`),
    "};",
    "",
    "export function getImageSize(src: string): ImageSize | undefined {",
    "  return IMAGE_SIZES[src];",
    "}",
    "",
  ];
  fs.writeFileSync(sizesOut, lines.join("\n"));
  console.log("Wrote", sizesOut);
}

async function main() {
  const files = fs.readdirSync(imagesDir).filter((f) => {
    const ext = path.extname(f).toLowerCase();
    return [".jpg", ".jpeg", ".webp"].includes(ext) && !SKIP.has(f);
  });

  const entries = {};
  for (const file of files) {
    console.log(file);
    const result = await optimizeFile(file);
    entries[result.key] = { width: result.width, height: result.height };
  }

  await writeImageSizes(entries);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
